# Generated by Django 5.0.1 on 2024-03-21 15:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='@', max_length=254)),
                ('name', models.CharField(default=' ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id_frequency', models.AutoField(primary_key=True, serialize=False)),
                ('frecuency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='History_events',
            fields=[
                ('id_event', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('delete_soft', models.BooleanField(default=False)),
                ('status_scan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='History_events_fails',
            fields=[
                ('id_history_events_fails', models.AutoField(primary_key=True, serialize=False)),
                ('img_route_err', models.CharField(max_length=300)),
                ('delete_soft', models.BooleanField(default=False)),
                ('fk_history_events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.history_events')),
            ],
        ),
        migrations.CreateModel(
            name='History_prices',
            fields=[
                ('id_history_prices', models.AutoField(primary_key=True, serialize=False)),
                ('price_scan', models.FloatField()),
                ('delete_soft', models.BooleanField(default=False)),
                ('fk_history_events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.history_events')),
            ],
        ),
        migrations.CreateModel(
            name='ImageTrack',
            fields=[
                ('id_image', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('x', models.DecimalField(decimal_places=20, max_digits=30)),
                ('y', models.DecimalField(decimal_places=20, max_digits=30)),
                ('width', models.DecimalField(decimal_places=20, max_digits=30)),
                ('height', models.DecimalField(decimal_places=20, max_digits=30)),
                ('rotate', models.DecimalField(decimal_places=20, max_digits=30)),
                ('scaleX', models.DecimalField(decimal_places=20, max_digits=30)),
                ('scaleY', models.DecimalField(decimal_places=20, max_digits=30)),
                ('url', models.CharField(max_length=500)),
                ('delete_soft', models.BooleanField(default=False)),
                ('notify_validate', models.BooleanField(default=False)),
                ('email_token', models.CharField(default=None, max_length=100)),
                ('client_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='screen.client')),
                ('frequency_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='screen.frequency')),
            ],
        ),
        migrations.AddField(
            model_name='history_events',
            name='fk_imagetrack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.imagetrack'),
        ),
    ]
