# Generated by Django 4.2.5 on 2024-04-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementsXpaths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default=None, max_length=200)),
                ('xpath', models.CharField(default=None, max_length=200)),
                ('type_element', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
