# Generated by Django 5.0.4 on 2024-05-08 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0003_error_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetrack',
            name='DateTimeTrack',
            field=models.CharField(default=datetime.datetime(2024, 5, 8, 22, 8, 59, 465315, tzinfo=datetime.timezone.utc)),
        ),
    ]
