# Generated by Django 5.0.1 on 2024-02-02 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0005_alter_imagetrack_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id_frequency', models.AutoField(primary_key=True, serialize=False)),
                ('frecuency', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='imagetrack',
            old_name='id',
            new_name='id_image',
        ),
        migrations.AddField(
            model_name='imagetrack',
            name='delete_soft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagetrack',
            name='frequency_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='screen.frequency'),
        ),
    ]
