# Generated by Django 5.0.4 on 2024-05-08 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0005_alter_imagetrack_datetimetrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetrack',
            name='DateTimeTrack',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 4, 16, 28, 849413, tzinfo=datetime.timezone.utc)),
        ),
    ]
