# Generated by Django 4.2.5 on 2024-02-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0006_frequency_rename_id_imagetrack_id_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='frecuency',
            field=models.CharField(max_length=50),
        ),
    ]
