# Generated by Django 5.0.4 on 2024-05-17 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0007_remove_imagetrack_frequency_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetrack',
            name='DateTimeTrack',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 16, 33, 3, 80296, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='imagetrack',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
