# Generated by Django 4.2.5 on 2024-02-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0007_alter_frequency_frecuency'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetrack',
            name='email',
            field=models.EmailField(default='@', max_length=254),
        ),
    ]
