# Generated by Django 4.2.5 on 2024-02-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0008_imagetrack_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetrack',
            name='email_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
