# Generated by Django 4.2.5 on 2024-02-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0009_imagetrack_email_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetrack',
            name='email_token',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
