# Generated by Django 5.0.4 on 2024-05-18 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0009_alter_imagetrack_datetimetrack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetrack',
            name='DateTimeTrack',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 21, 31, 51, 467509, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='imagetrack',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
