# Generated by Django 4.2.5 on 2024-02-12 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0010_imagetrack_email_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='@', max_length=254)),
                ('email_confirm', models.BooleanField(default=False)),
                ('email_token', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagetrack',
            name='email',
        ),
        migrations.RemoveField(
            model_name='imagetrack',
            name='email_confirm',
        ),
        migrations.RemoveField(
            model_name='imagetrack',
            name='email_token',
        ),
        migrations.AddField(
            model_name='imagetrack',
            name='client_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='screen.client'),
        ),
    ]
