# Generated by Django 5.0.4 on 2024-06-01 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0012_contact_form_alter_error_form_date_log_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_form',
            name='name_contact',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='error_form',
            name='date_log_error',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 21, 5, 46, 428890, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='imagetrack',
            name='DateTimeTrack',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 21, 5, 46, 427888, tzinfo=datetime.timezone.utc)),
        ),
    ]
