# Generated by Django 4.2.5 on 2024-02-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0012_remove_client_email_confirm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email_token',
        ),
        migrations.AddField(
            model_name='imagetrack',
            name='email_token',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
