# Generated by Django 5.0.4 on 2024-08-08 14:28

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0013_contact_form_name_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBasic',
            fields=[
                ('idImage', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(default=None, max_length=40)),
                ('EmailContact', models.EmailField(max_length=254, null=None)),
            ],
        ),
        migrations.AlterField(
            model_name='error_form',
            name='date_log_error',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 9, 27, 59, 234329, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='imagetrack',
            name='DateTimeTrack',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 9, 27, 59, 232329, tzinfo=datetime.timezone.utc)),
        ),
    ]
