# Generated by Django 4.2.5 on 2024-02-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0013_remove_client_email_token_imagetrack_email_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
