# Generated by Django 4.2.5 on 2024-02-28 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0014_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_events',
            fields=[
                ('id_event', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('price_scan', models.FloatField()),
                ('delete_soft', models.BooleanField(default=False)),
                ('fk_imagetrack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.imagetrack')),
            ],
        ),
        migrations.CreateModel(
            name='History_prices',
            fields=[
                ('id_history_prices', models.AutoField(primary_key=True, serialize=False)),
                ('price_scan', models.FloatField()),
                ('delete_soft', models.BooleanField(default=False)),
                ('fk_history_events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.history_events')),
            ],
        ),
        migrations.CreateModel(
            name='History_events_fails',
            fields=[
                ('id_history_events_fails', models.AutoField(primary_key=True, serialize=False)),
                ('img_route_err', models.CharField(max_length=300)),
                ('delete_soft', models.BooleanField(default=False)),
                ('fk_history_events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.history_events')),
            ],
        ),
    ]
