# Generated by Django 4.2.5 on 2024-02-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0015_history_events_history_prices_history_events_fails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_events',
            name='price_scan',
        ),
    ]
