# Generated by Django 4.2.5 on 2024-02-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0016_remove_history_events_price_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_events',
            name='status_scan',
            field=models.BooleanField(default=False),
        ),
    ]
