# Generated by Django 4.2.5 on 2024-02-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0017_history_events_status_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_events',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
